import React, { useEffect, useState, useMemo } from "react";
import {
  ConnectionProvider,
  WalletProvider,
  useAnchorWallet,
  useConnection,
} from "@solana/wallet-adapter-react";
import {
  WalletModalProvider,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import { PhantomWalletAdapter } from "@solana/wallet-adapter-wallets";
import { Program, AnchorProvider, utils, web3 } from "@coral-xyz/anchor";
import { PublicKey, SystemProgram } from "@solana/web3.js";
import "@solana/wallet-adapter-react-ui/styles.css";

// Import the IDL generated by Anchor
import idl from "./e_voting.json";

// --- Main App Wrapper with Wallet Context ---
export default function App() {
  const endpoint = web3.clusterApiUrl("devnet");
  const wallets = useMemo(() => [new PhantomWalletAdapter()], []);

  return (
    <ConnectionProvider endpoint={endpoint}>
      <WalletProvider wallets={wallets} autoConnect>
        <WalletModalProvider>
          <div
            style={{
              maxWidth: "800px",
              margin: "0 auto",
              padding: "20px",
              fontFamily: "sans-serif",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                marginBottom: "20px",
              }}
            >
              <h1>E-Voting DApp</h1>
              <WalletMultiButton />
            </div>
            <VotingDashboard />
          </div>
        </WalletModalProvider>
      </WalletProvider>
    </ConnectionProvider>
  );
}

// --- Dashboard Component ---
function VotingDashboard() {
  const { connection } = useConnection();
  const wallet = useAnchorWallet();
  const [proposals, setProposals] = useState<any[]>([]);
  const [description, setDescription] = useState("");
  const [pid, setPid] = useState(1);

  // Setup Anchor Program instance
  const program = useMemo(() => {
    if (!wallet) return null;
    const provider = new AnchorProvider(connection, wallet, {
      preflightCommitment: "processed",
    });
    return new Program(idl as any, provider);
  }, [connection, wallet]);

  // Fetch all proposals on load
  const fetchProposals = async () => {
    if (!program) return;
    try {
      const allProposals = await program.account.proposal.all();
      setProposals(allProposals);
    } catch (err) {
      console.error("Error fetching proposals:", err);
    }
  };

  useEffect(() => {
    fetchProposals();
  }, [program]);

  // Handle Proposal Creation
  const handleCreateProposal = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!program || !wallet) return;

    try {
      // 1. Derive the PDA for the Proposal account based on seeds in Rust
      const [proposalPda] = PublicKey.findProgramAddressSync(
        [
          utils.bytes.utf8.encode("proposal"),
          wallet.publicKey.toBuffer(),
          new Uint8Array([pid]),
        ],
        program.programId,
      );

      // 2. Call the create instruction
      await program.methods
        .create(pid, description)
        .accounts({
          proposal: proposalPda,
          user: wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      alert("Proposal created successfully!");
      setDescription("");
      setPid(pid + 1);
      fetchProposals(); // Refresh the list
    } catch (err) {
      console.error("Error creating proposal:", err);
      alert("Failed to create proposal. See console.");
    }
  };

  // Handle Voting (Yes or No)
  const handleVote = async (
    proposalPubkey: PublicKey,
    voteType: "yes" | "no",
  ) => {
    if (!program || !wallet) return;

    try {
      // 1. Derive the PDA for the Vote account
      const [votePda] = PublicKey.findProgramAddressSync(
        [
          utils.bytes.utf8.encode("vote"),
          proposalPubkey.toBuffer(),
          wallet.publicKey.toBuffer(),
        ],
        program.programId,
      );

      // 2. Select the method based on user choice
      const method =
        voteType === "yes"
          ? program.methods.voteYes()
          : program.methods.voteNo();

      // 3. Call the instruction
      await method
        .accounts({
          proposal: proposalPubkey,
          user: wallet.publicKey,
          vote: votePda,
          systemProgram: SystemProgram.programId,
        })
        .rpc();

      alert(`Voted ${voteType} successfully!`);
      fetchProposals(); // Refresh vote counts
    } catch (err: any) {
      console.error("Error voting:", err);
      if (err.message.includes("already in use")) {
        alert("You have already voted on this proposal!");
      } else {
        alert("Failed to vote. See console.");
      }
    }
  };

  if (!wallet) {
    return <h3>Please connect your wallet to view and create proposals.</h3>;
  }

  return (
    <div>
      {/* Create Proposal Form */}
      <div
        style={{
          padding: "20px",
          border: "1px solid #ccc",
          borderRadius: "8px",
          marginBottom: "20px",
        }}
      >
        <h2>Create a Proposal</h2>
        <form onSubmit={handleCreateProposal}>
          <div style={{ marginBottom: "10px" }}>
            <label>Proposal ID (PID): </label>
            <input
              type="number"
              value={pid}
              onChange={(e) => setPid(Number(e.target.value))}
              min="0"
              max="255"
              required
            />
          </div>
          <div style={{ marginBottom: "10px" }}>
            <label>Description: </label>
            <input
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              maxLength={50}
              required
              style={{ width: "300px" }}
            />
          </div>
          <button
            type="submit"
            style={{ padding: "10px 20px", cursor: "pointer" }}
          >
            Create Proposal
          </button>
        </form>
      </div>

      {/* List of Proposals */}
      <h2>Active Proposals</h2>
      {proposals.length === 0 ? (
        <p>No proposals found.</p>
      ) : (
        <div style={{ display: "grid", gap: "15px" }}>
          {proposals.map((p, index) => (
            <div
              key={index}
              style={{
                padding: "15px",
                border: "1px solid #eee",
                borderRadius: "8px",
                background: "#f9f9f9",
              }}
            >
              <h3 style={{ margin: "0 0 10px 0" }}>
                #{p.account.pid} - {p.account.description}
              </h3>
              <p>
                <strong>Status:</strong>{" "}
                {p.account.ongoing ? "🟢 Active" : "🔴 Closed"}
              </p>
              <p>
                <strong>Creator:</strong>{" "}
                {p.account.owner.toString().slice(0, 8)}...
              </p>

              <div
                style={{
                  display: "flex",
                  gap: "20px",
                  alignItems: "center",
                  marginTop: "15px",
                }}
              >
                <div>
                  <span
                    style={{
                      fontSize: "20px",
                      fontWeight: "bold",
                      color: "green",
                    }}
                  >
                    {p.account.yesVotes}
                  </span>
                  <button
                    onClick={() => handleVote(p.publicKey, "yes")}
                    style={{
                      marginLeft: "10px",
                      cursor: "pointer",
                      background: "#d4edda",
                      border: "1px solid #c3e6cb",
                    }}
                  >
                    Vote YES
                  </button>
                </div>
                <div>
                  <span
                    style={{
                      fontSize: "20px",
                      fontWeight: "bold",
                      color: "red",
                    }}
                  >
                    {p.account.noVotes}
                  </span>
                  <button
                    onClick={() => handleVote(p.publicKey, "no")}
                    style={{
                      marginLeft: "10px",
                      cursor: "pointer",
                      background: "#f8d7da",
                      border: "1px solid #f5c6cb",
                    }}
                  >
                    Vote NO
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
